import RAID_PLAN from '../../../inbox/the-twin-fangs.png'
import type { EvidenceEncounterDefinition } from '../../platform/encounters/evidenceFullFight'

export const definition = {
  id: 'the-twin-fangs', name: 'The Twin Fangs', order: 6,
  summary: 'Control Eternal Venom, clear Caustic Globules, rotate Feast groups, and keep Vexhul and Ithraz synchronized.',
  sourceAsOf: '2026-08-16', sourceNote: 'Reconciled pre-live guide and spell data; counts and recurrence remain configurable pending live logs.',
  arenaKind: 'triangle-ring', arena2dId: 'twin_fangs_raidplan', arena2dLabel: 'Twin Fangs supplied triangular raid plan', learn2dBackground: RAID_PLAN, boardClass: 'twin-fangs-2d-board', start: { x: 0, z: 24 },
  arena3d: { id: 'twin_fangs_triangle_world', label: 'Twin Fangs toxic-depths ring', shape: 'rectangle', width: 88, depth: 80, anchors: [{ id: 'vexhul', label: 'Vexhul', x: -24, z: 12 }, { id: 'ithraz', label: 'Ithraz', x: 24, z: 12 }, { id: 'feast', label: 'Feast groups', x: 0, z: 25 }, { id: 'submerge', label: 'Submerge route', x: 0, z: -32 }], theme: { kind: 'twin-fangs', layout: 'triangle-ring', surroundings: 'toxic-depths', platform: 'floating', material: 'blood-venom-ring', floor: '#211c22', boundary: '#af765d', accent: '#d0a45b', poison: '#9acb24', fog: 'toxic-haze' } },
  bosses: [{ id: 'twin-vexhul', name: 'Vexhul', position: { x: -24, z: 12 }, color: '#79b868' }, { id: 'twin-ithraz', name: 'Ithraz', position: { x: 24, z: 12 }, color: '#b75a62' }],
  phaseNames: ['Venom economy', 'Ravenous Feast', 'Submerge'], resource: { label: 'Eternal Venom', initial: 1, maximum: 9, lethal: 9 },
  tacticFields: [{ id: 'feast-groups', label: 'Ravenous Feast groups', kind: 'group', value: ['feast-one', 'feast-two', 'feast-three'] }, { id: 'globule-soakers', label: 'Caustic Globule soakers', kind: 'group', value: ['low-stack-one', 'low-stack-two'] }, { id: 'bulwark-kicks', label: 'Barbed Bulwark interrupts', kind: 'action-owner', value: 'player' }],
  steps: [
    { id: 'caustic-deluge', label: 'Caustic Deluge', prompt: 'Leave Vexhul splash impacts while preserving tank range.', advice: 'Move outside the four-yard acid impact.', duration2d: 4, duration3d: 5, position: { x: -24, z: 12 }, radius: 9, intent: 'avoid', color: '#78bf68', failureResourceDelta: 1 },
    { id: 'caustic-globule', label: 'Caustic Globule', prompt: 'Consume your assigned globule before its ten-second rupture.', advice: 'Reach the highlighted globule with enough venom headroom.', duration2d: 6, duration3d: 8, position: { x: -34, z: 17 }, radius: 5, intent: 'enter', color: '#a5d45f', resourceDelta: 1, failureResourceDelta: 1 },
    { id: 'barbed-bulwark', label: 'Barbed Bulwark', prompt: 'Interrupt the shield before the globule can be soaked.', advice: 'Use Interrupt on the active Bulwark before its owner ruptures.', duration2d: 5, duration3d: 6, position: { x: -30, z: 15 }, radius: 5, intent: 'action', color: '#b389d3', requiredAction: 'interrupt', failureResourceDelta: 1 },
    { id: 'stir-depths', label: 'Stir the Depths', prompt: 'Move through the safe gap between venom waves.', advice: 'Leave the incoming wave lane to avoid another venom stack.', duration2d: 5, duration3d: 6, position: { x: 0, z: -28 }, radius: 9, intent: 'avoid', color: '#71b879', failureResourceDelta: 1 },
    { id: 'ravenous-feast-one', label: 'Ravenous Feast I', prompt: 'Join only your assigned Feast strike to remove Eternal Venom.', advice: 'Enter your Feast group and avoid consuming another group.', duration2d: 5, duration3d: 6, position: { x: 0, z: 25 }, radius: 8, intent: 'enter', color: '#d36e72', resourceDelta: -1 },
    { id: 'stone-breaker-one', label: 'Stone Breaker I', prompt: 'Recover from the push and catch the first tank soak.', advice: 'Enter the first sequential Stone Breaker marker.', duration2d: 4, duration3d: 5, position: { x: 30, z: 14 }, radius: 5, intent: 'enter', color: '#d3b36d', launchVelocity: 4.4 },
    { id: 'stone-breaker-two', label: 'Stone Breaker II', prompt: 'Move to the second tank soak without reusing another player.', advice: 'Follow the displayed Stone Breaker order.', duration2d: 4, duration3d: 5, position: { x: 34, z: 3 }, radius: 5, intent: 'enter', color: '#d3b36d' },
    { id: 'stone-breaker-three', label: 'Stone Breaker III', prompt: 'Catch the third slam and prepare the boss swap.', advice: 'Complete all three tank soaks before swapping serpents.', duration2d: 4, duration3d: 5, position: { x: 27, z: -8 }, radius: 5, intent: 'enter', color: '#d3b36d' },
    { id: 'corrosive-spit', label: 'Corrosive Spit', prompt: 'Aim the add line away from the raid and leave its path.', advice: 'Move out of the projected Spit line.', duration2d: 5, duration3d: 6, position: { x: -6, z: 24 }, radius: 7, intent: 'avoid', color: '#8ac25e', failureResourceDelta: 1 },
    { id: 'submerge', label: 'Submerge', prompt: 'Follow the safe triangular ring while both serpents reposition.', advice: 'Move to the announced Submerge anchor without entering the central void.', duration2d: 6, duration3d: 8, position: { x: 0, z: -34 }, radius: 7, intent: 'enter', color: '#bc7185' },
    { id: 'ravenous-feast-two', label: 'Ravenous Feast II', prompt: 'Use the final assigned Feast to restore venom headroom.', advice: 'Join the correct group before the paired bosses reach execute range.', duration2d: 5, duration3d: 6, position: { x: 0, z: 25 }, radius: 8, intent: 'enter', color: '#d36e72', resourceDelta: -2 },
  ],
} as const satisfies EvidenceEncounterDefinition
