import type { AbilityDefinition } from '../../platform/encounters'
import { journalHigh, ptrMedium } from './research'

export const abilities = [
  {
    id: 'sentinels_dominance',
    name: "Ula'tek's Dominance",
    description: 'Keep the two bosses separated to avoid their near-total damage reduction.',
    severity: 'warning',
    tags: ['movement', 'tank'],
    timings: [],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_marks',
    name: 'Mark of Acid / Mark of Blood',
    description: 'Each boss applies its stacking side mark during active phases.',
    severity: 'warning',
    tags: ['aura', 'movement'],
    timings: [
      { key: 'application-interval', seconds: 5, provenance: journalHigh },
      { key: 'aura-duration', seconds: 40, provenance: journalHigh },
    ],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_vitriolic_stasis',
    name: 'Vitriolic Stasis',
    description: 'At full energy both bosses become nearly immune and the raid solves the Stasis puzzle.',
    severity: 'warning',
    tags: ['informational', 'movement'],
    timings: [{ key: 'duration', seconds: 30, provenance: journalHigh }],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_helical_toxins',
    name: 'Helical Toxins',
    description: 'Match red and green toxin compositions so a pair combines to exactly four green.',
    severity: 'lethal',
    tags: ['pair', 'movement'],
    timings: [{ key: 'matching-window', seconds: 28, provenance: journalHigh }],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_toxic_droplets',
    name: 'Toxic Droplets',
    description: 'Assigned Acid-side players intercept droplets before they explode.',
    severity: 'lethal',
    tags: ['object', 'soak'],
    timings: [{ key: 'explosion-delay', seconds: 12, provenance: journalHigh }],
    provenance: ptrMedium,
  },
  {
    id: 'sentinels_venom_coagulation',
    name: 'Venom Coagulation',
    description: 'A living slime emits Contaminate until the raid switches target and kills it.',
    severity: 'lethal',
    tags: ['add', 'informational'],
    timings: [],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_living_venom',
    name: 'Living Venom',
    description: 'Outgoing venom lanes return through the Acid side after a short delay.',
    severity: 'lethal',
    tags: ['movement'],
    timings: [{ key: 'return-delay', seconds: 4, provenance: ptrMedium }],
    provenance: ptrMedium,
  },
  {
    id: 'sentinels_unstable_miasma',
    name: 'Unstable Miasma',
    description: 'The Blood-side group shares the impact before placing its resulting pool at the edge.',
    severity: 'lethal',
    tags: ['stack', 'soak', 'object'],
    timings: [{ key: 'aura-duration', seconds: 8, provenance: journalHigh }],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_blighted_blood',
    name: 'Blighted Blood',
    description: 'A healer-dispellable Blood-side infection that creates Blood Venom if allowed to expire.',
    severity: 'lethal',
    tags: ['aura', 'dispel', 'object'],
    timings: [{ key: 'aura-duration', seconds: 18, provenance: journalHigh }],
    provenance: journalHigh,
  },
  {
    id: 'sentinels_shifting_protovenom',
    name: 'Shifting Protovenom',
    description: 'Marked partners meet in assigned lanes without touching unmarked or incorrect players.',
    severity: 'lethal',
    tags: ['pair', 'movement'],
    timings: [],
    provenance: ptrMedium,
  },
] as const satisfies readonly AbilityDefinition[]
