import { expect, test } from '@playwright/test'

test('boots the standalone Season 2 shell with the first package runtimes ready', async ({ page }) => {
  await page.goto('/')

  await expect(page).toHaveTitle('Midnight Season 2 Trainer')
  await expect(page.getByRole('heading', { name: 'Midnight Season 2 Trainer' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Entombed Sentinels' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Learn 2D' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Train 3D' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Launch Learn 2D' })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Launch Train 3D' })).toBeEnabled()
  await expect(page.getByLabel('Encounter catalogue').getByText('Coming soon').first()).toBeVisible()
  await expect(page.locator('.season2-encounter')).toHaveCount(0)
  await expect(page.getByLabel('Build information')).toContainText(/v\d+\.\d+\.\d+ · [a-z0-9]+ ·/)
  await expect(page.getByRole('link', { name: 'Changelog ↗' })).toBeVisible()
  await expect(page.getByLabel('About Pestivator')).toContainText('pestivator#2515')
  await expect(page.getByRole('heading', { name: 'L’ura Trainer' })).toHaveCount(0)
})

test('moves independently in all four Learn 2D directions and clears input on blur', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Launch Learn 2D' }).click()
  const player = page.getByLabel('Controlled character with 1 green and 3 red toxins')
  const position = async () => ({ x: Number(await player.getAttribute('data-position-x')), y: Number(await player.getAttribute('data-position-y')) })
  let before = await position()
  await page.keyboard.down('a'); await page.waitForTimeout(260); await page.keyboard.up('a')
  let after = await position(); expect(after.x).toBeLessThan(before.x)
  before = after
  await page.keyboard.down('d'); await page.waitForTimeout(420); await page.keyboard.up('d')
  after = await position(); expect(after.x).toBeGreaterThan(before.x)
  before = after
  await page.keyboard.down('s'); await page.waitForTimeout(260); await page.keyboard.up('s')
  after = await position(); expect(after.y).toBeGreaterThan(before.y)
  before = after
  await page.keyboard.down('w'); await page.waitForTimeout(260); await page.keyboard.up('w')
  after = await position(); expect(after.y).toBeLessThan(before.y)

  await page.keyboard.down('w'); await page.waitForTimeout(180)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.waitForTimeout(100)
  const stopped = await position()
  await page.waitForTimeout(300)
  expect(Math.abs((await position()).y - stopped.y)).toBeLessThan(.2)
  await page.keyboard.up('w')
})

test('keeps the wide runtime header in one line and preserves the 2D arena aspect', async ({ page }) => {
  await page.setViewportSize({ width: 2048, height: 900 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Launch Learn 2D' }).click()

  await expect(page.getByLabel('Build information')).toHaveCount(0)
  const status = page.locator('.runtime-status-bar')
  const statusBox = await status.boundingBox()
  expect(statusBox?.width).toBeGreaterThan(1900)
  const boardBox = await page.getByLabel('Movable Helical Toxins tactical diagram').boundingBox()
  if (!boardBox) throw new Error('2D arena has no bounds')
  expect(boardBox.width / boardBox.height).toBeCloseTo(5 / 3, 2)
  await expect(page.getByRole('complementary', { name: 'Recent failures' })).toContainText('No failures yet')
  await expect(page.getByRole('complementary', { name: 'Points' })).toContainText('Not scored')
})

test('moves the player through the Helical Toxins Learn 2D icon drill', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Launch Learn 2D' }).click()

  await expect(page.getByRole('heading', { name: 'Helical Toxins tutorial' })).toBeVisible()
  await expect(page.getByLabel('Controlled character with 1 green and 3 red toxins')).toBeVisible()
  await expect(page.getByRole('img', { name: '3 green toxins and 1 red toxin' })).toBeVisible()
  await page.keyboard.down('w')
  await page.waitForTimeout(1800)
  await page.keyboard.up('w')
  await page.keyboard.down('d')
  await page.waitForTimeout(950)
  await page.keyboard.up('d')
  await expect(page.getByText('Resolved: your pair combines to exactly four green.')).toBeVisible()
})

test('opens paired contract rooms with full-raid ground reactions and paced 3D rendering', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Open Learn 2D room' }).click()

  await expect(page.getByRole('heading', { name: 'Top-down reaction lab' })).toBeVisible()
  const entrance = page.getByRole('dialog', { name: 'Contract room entrance' })
  await expect(entrance).toBeVisible()
  await expect(page.getByLabel(/ground rune$/)).toHaveCount(4)
  await expect(page.getByLabel(/NPC$/)).toHaveCount(19)
  const player2d = page.getByLabel(/Controlled ranged player/)
  const lockedY = await player2d.getAttribute('data-position-y')
  await page.keyboard.down('w'); await page.waitForTimeout(220); await page.keyboard.up('w')
  await expect(player2d).toHaveAttribute('data-position-y', lockedY || '')
  await entrance.getByLabel('Player role').selectOption('tank')
  await expect(page.getByLabel(/Controlled tank player/)).toBeVisible()
  await expect(page.getByLabel('tank NPC')).toHaveCount(1)
  await entrance.getByRole('button', { name: 'Start 3…2…1' }).click()
  await expect(page.getByLabel('Pull countdown')).toBeVisible()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect(page.getByLabel('Contract combat actions')).toHaveCount(0)
  await expect(page.getByText(/no Main ability or potion in Learn 2D/)).toBeVisible()
  await expect(page.locator('.learn2d-character .actor-health')).toHaveCount(1)
  await expect(page.locator('.contract-2d-boss .actor-health')).toHaveCount(1)
  await page.getByRole('button', { name: 'Exit' }).click()
  await page.getByRole('button', { name: 'Open Train 3D room' }).click()

  await expect(page.getByRole('heading', { name: 'Reaction and movement lab' })).toBeVisible()
  const contractArena = page.getByLabel('Third-person 3D training arena')
  await expect(contractArena).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Contract room entrance' })).toBeVisible()
  await expect(page.locator('details.contract-lab-drawer')).not.toHaveAttribute('open', '')
  await page.getByRole('dialog', { name: 'Contract room entrance' }).getByRole('button', { name: 'Start 3…2…1' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toContainText('event 1')
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toContainText('20-player raid')
  await expect(page.locator('.arena-hud-health.player')).toBeVisible()
  await expect(page.locator('.arena-hud-health.boss')).toBeVisible()
  await expect(page.getByRole('button', { name: /Main ability/ })).toBeVisible()
  await expect.poll(async () => Number(await contractArena.getAttribute('data-render-fps')), { timeout: 4000 }).toBeGreaterThanOrEqual(30)
  expect(Number(await contractArena.getAttribute('data-frame-p95-ms'))).toBeLessThan(50)
  await expect(page.getByText(/\d+ FPS · p95/)).toBeVisible()
})

test('uses rebound movement keys and shared HUD settings in the Helical Toxins 3D drill', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Keys & Mouse' }).click()
  await page.getByRole('button', { name: 'Rebind forward, current W' }).click()
  await page.keyboard.press('ArrowUp')
  await page.reload()
  await page.getByRole('button', { name: 'Keys & Mouse' }).click()
  await expect(page.getByRole('button', { name: 'Rebind forward, current ArrowUp' })).toBeVisible()
  await page.getByRole('button', { name: 'HUD' }).click()
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toHaveCount(0)
  await expect(page.getByLabel('Draggable HUD preview')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Player health + cooldowns' })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Show objective' }).uncheck()
  await page.getByRole('button', { name: 'Game settings' }).click()
  await page.getByRole('button', { name: 'Launch Train 3D' }).click()

  await expect(page.getByRole('heading', { name: 'Helical Toxins movement drill' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Contract room entrance' })).toHaveCount(0)
  await expect(page.locator('.contract-lab-drawer')).toHaveCount(0)
  const arena = page.getByLabel('Third-person 3D training arena')
  await expect(arena).toBeVisible()
  await arena.hover()
  await page.mouse.wheel(0, 300)
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('midnight-s2:training-settings:v1') || '{}').camera?.zoom ?? 0)).toBeGreaterThan(22)
  await expect(page.getByRole('complementary', { name: 'Training HUD' }).getByText('Objective')).toHaveCount(0)
  await page.keyboard.press('p')
  await expect(page.getByRole('button', { name: /Resume P/ })).toBeVisible()
  const pausedAt = { x: await arena.getAttribute('data-player-x'), z: await arena.getAttribute('data-player-z') }
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(300); await page.keyboard.up('ArrowUp')
  await expect(arena).toHaveAttribute('data-player-x', pausedAt.x || '')
  await expect(arena).toHaveAttribute('data-player-z', pausedAt.z || '')
  await page.keyboard.press('p')
  await page.keyboard.down('ArrowUp')
  await page.waitForTimeout(500)
  await page.keyboard.up('ArrowUp')
  await expect(page.getByRole('complementary', { name: 'Training HUD' }).getByText(/-22\.0 · -/)).toBeVisible()
})

test('Season 2 shell HUD boxes follow the pointer and persist on release', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'HUD' }).click()
  const preview = page.getByLabel('Draggable HUD preview')
  const player = page.getByRole('button', { name: 'Player health + cooldowns' })
  await player.hover()
  const before = await player.boundingBox()
  if (!before) throw new Error('HUD player box has no bounds')
  await page.mouse.down()
  await page.mouse.move(before.x + before.width / 2 + 160, before.y + before.height / 2 + 60, { steps: 3 })
  await expect.poll(async () => (await player.boundingBox())!.x - before.x, { timeout: 500 }).toBeGreaterThan(145)
  await expect.poll(async () => (await player.boundingBox())!.y - before.y, { timeout: 500 }).toBeGreaterThan(45)
  await page.mouse.up()
  const previewBox = await preview.boundingBox()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('midnight-s2:training-settings:v1') || '{}').hud?.layout?.player)
  if (!previewBox) throw new Error('HUD preview has no bounds')
  expect(saved.x).toBeGreaterThan(35)
  await expect.poll(() => player.evaluate(element => Number.parseFloat((element as HTMLElement).style.left))).toBe(saved.x)
  const after = await player.boundingBox()
  if (!after) throw new Error('Moved HUD player box has no bounds')
  expect(Math.abs((after.x - before.x) - (saved.x - 21) / 100 * previewBox.width)).toBeLessThan(2)
  expect(Math.abs((after.y - before.y) - (saved.y - 53) / 100 * previewBox.height)).toBeLessThan(2)
  expect(saved.y).toBeGreaterThan(53)
  await expect(preview).toBeVisible()
})

test('keeps left orbit independent, aligns on right press, and moves with both mouse buttons', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Launch Train 3D' }).click()
  const arena = page.getByLabel('Third-person 3D training arena')
  const bounds = await arena.boundingBox()
  if (!bounds) throw new Error('3D arena has no bounds')
  const center = { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 }
  await page.mouse.move(center.x, center.y)
  await page.mouse.down({ button: 'left' })
  await page.mouse.move(center.x + 90, center.y)
  await page.mouse.up({ button: 'left' })
  expect(Number(await arena.getAttribute('data-player-facing'))).toBeCloseTo(0, 2)

  await page.mouse.down({ button: 'right' })
  await expect.poll(async () => Number(await arena.getAttribute('data-player-facing'))).toBeGreaterThan(.25)
  const alignedFacing = Number(await arena.getAttribute('data-player-facing'))
  await page.mouse.move(center.x + 130, center.y)
  await expect.poll(async () => Number(await arena.getAttribute('data-player-facing'))).toBeGreaterThan(alignedFacing)

  const before = { x: Number(await arena.getAttribute('data-player-x')), z: Number(await arena.getAttribute('data-player-z')) }
  await page.mouse.down({ button: 'left' })
  await expect.poll(async () => {
    const current = { x: Number(await arena.getAttribute('data-player-x')), z: Number(await arena.getAttribute('data-player-z')) }
    return Math.hypot(current.x - before.x, current.z - before.z)
  }).toBeGreaterThan(2)
  await page.mouse.up({ button: 'left' })
  await page.mouse.up({ button: 'right' })
  await expect(arena).toHaveAttribute('data-player-marker', 'humanoid-chevron')
})

test('retains the v0.9.1 source application behind a development-only reference route', async ({ page }) => {
  await page.goto('/?reference=lura-v0.9.1')
  await expect(page.getByRole('heading', { name: 'L’ura Trainer' })).toBeVisible()
})
