import { expect, test, type Page } from '@playwright/test'

async function selectBoss(page: Page, name: string) {
  await page.getByRole('navigation', { name: 'Boss fight selector' }).getByRole('button', { name: new RegExp(name) }).click()
}

test('boots the standalone Season 2 shell with the first package runtimes ready', async ({ page }) => {
  await page.goto('/')

  await expect(page).toHaveTitle('Midnight Season 2 Trainer')
  await expect(page.getByRole('heading', { name: 'Midnight Season 2 Trainer' })).toBeVisible()
  await expect(page.getByRole('heading', { name: "Nek'zali the Soulcoiler" })).toBeVisible()
  await selectBoss(page, 'Entombed Sentinels')
  await expect(page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' })).toContainText('Learn 2D')
  await expect(page.getByRole('button', { name: 'Launch Entombed Sentinels Train 3D' })).toContainText('Train 3D')
  await expect(page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Launch Entombed Sentinels Train 3D' })).toBeEnabled()
  const trainerDifficulty = page.getByRole('group', { name: 'Trainer difficulty' })
  for (const profile of ['Test', 'Easy', 'Normal', 'Hard']) await expect(trainerDifficulty.getByRole('button', { name: profile })).toBeVisible()
  await expect(page.getByLabel('Encounter catalogue')).not.toContainText(/Heroic|Mythic/)
  await expect(page.getByRole('navigation', { name: 'Boss fight selector' }).getByText('Planned').first()).toBeVisible()
  await expect(page.locator('.season2-encounter')).toHaveCount(0)
  await expect(page.getByLabel('Build information')).toContainText(/v\d+\.\d+\.\d+ · [a-z0-9]+ ·/)
  await expect(page.getByRole('link', { name: 'Changelog ↗' })).toBeVisible()
  await expect(page.getByLabel('About Pestivator')).toContainText('pestivator#2515')
  await expect(page.getByRole('heading', { name: 'L’ura Trainer' })).toHaveCount(0)
  await expect(page.getByText(/public deployment disabled|platform extraction/i)).toHaveCount(0)
})

test('persists a versioned tactic and independent audio channels locally', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Tactical plan' }).click()
  await expect(page.getByLabel(/draggable raid plan/)).toBeVisible()
  await expect(page.locator('.tactical-actor.player')).toHaveCount(20)
  await expect(page.locator('.tactical-actor.boss')).not.toHaveCount(0)
  const phaseOneTank = page.getByRole('button', { name: 'Move T1 in Phase 1' })
  const board = page.getByLabel(/Phase 1 draggable raid plan/)
  await phaseOneTank.scrollIntoViewIfNeeded()
  const [tankBefore, boardBox] = await Promise.all([phaseOneTank.boundingBox(), board.boundingBox()])
  if (!tankBefore || !boardBox) throw new Error('Planner actor or board has no bounds')
  const tankLeftBefore = Number.parseFloat(await phaseOneTank.evaluate(element => (element as HTMLElement).style.left))
  await page.mouse.move(tankBefore.x + tankBefore.width / 2, tankBefore.y + tankBefore.height / 2)
  await page.mouse.down()
  await page.mouse.move(boardBox.x + boardBox.width * .18, boardBox.y + boardBox.height * .72, { steps: 5 })
  await page.mouse.up()
  const movedTankLeft = Number.parseFloat(await phaseOneTank.evaluate(element => (element as HTMLElement).style.left))
  expect(Math.abs(movedTankLeft - tankLeftBefore)).toBeGreaterThan(20)
  await page.getByRole('button', { name: 'Echo intermission' }).click()
  const intermissionTankLeft = Number.parseFloat(await page.getByRole('button', { name: 'Move T1 in Echo intermission' }).evaluate(element => (element as HTMLElement).style.left))
  expect(Math.abs(intermissionTankLeft - movedTankLeft)).toBeGreaterThan(20)
  await page.getByRole('button', { name: 'Phase 1', exact: true }).click()
  await page.getByLabel('Plan name').fill('Travel playtest plan')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('phase positions saved in this browser')
  const tactic = await page.evaluate(() => JSON.parse(localStorage.getItem('midnight-s2:tactic:v2:nekzali') ?? 'null'))
  expect(tactic).toMatchObject({ format: 'midnight-season-2-tactic', version: 2, encounterId: 'nekzali', tactic: { name: 'Travel playtest plan', schemaVersion: 2 } })
  expect(Object.keys(tactic.layouts)).toEqual(['nekzali_phase_1', 'nekzali_intermission', 'nekzali_phase_2', 'nekzali_well_realm'])
  expect(tactic.layouts.nekzali_phase_1['tank-1']).not.toEqual(tactic.layouts.nekzali_intermission['tank-1'])

  await page.getByRole('button', { name: 'Audio' }).click()
  await page.getByLabel('Enable encounter sounds').check()
  await page.reload()
  await page.getByRole('button', { name: 'Audio' }).click()
  await expect(page.getByLabel('Enable encounter sounds')).toBeChecked()
})

test("discovers all raid bosses and launches Nek'zali in separate 2D and 3D arenas", async ({ page }) => {
  await page.goto('/')
  const catalogue = page.getByRole('navigation', { name: 'Boss fight selector' })
  for (const boss of ["Nek'zali the Soulcoiler", 'Entombed Sentinels', 'Vashnik the Malignant', 'The Lost Explorers', 'Sszorak', 'The Twin Fangs', 'The Coiled Altar', "Ula'tek"]) {
    await expect(catalogue.getByRole('button', { name: new RegExp(boss) })).toBeVisible()
  }
  await expect(page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" })).toBeEnabled()
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" }).click()
  const setup2d = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await expect(setup2d).toContainText('Choose role and assignment')
  await expect(setup2d).toContainText(/(?:Pyre soak|Cremation cleanup)/i)
  await expect(page.getByLabel("Nek'zali raid-plan training arena")).toBeVisible()
  await setup2d.getByRole('button', { name: /Tank 1, warrior/ }).click()
  await expect(setup2d).toContainText(/(?:Pyre soak|Cremation cleanup)/i)
  await setup2d.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  const player = page.getByLabel('Controlled warrior tank player')
  const raidLead = page.getByLabel('Raid lead mechanic telegraph')
  await expect(raidLead).toBeVisible()
  await expect(raidLead).toContainText('Now')
  await expect(raidLead).toContainText('Soulcoil Ignition')
  const raidLeadStyle = await raidLead.evaluate(element => ({
    background: getComputedStyle(element).backgroundColor,
    color: getComputedStyle(element).color,
    left: element.getBoundingClientRect().left - element.parentElement!.getBoundingClientRect().left,
    top: element.getBoundingClientRect().top - element.parentElement!.getBoundingClientRect().top,
  }))
  expect(raidLeadStyle.background).toBe('rgba(243, 216, 113, 0.96)')
  expect(raidLeadStyle.color).toBe('rgb(23, 18, 8)')
  expect(raidLeadStyle.left).toBeGreaterThanOrEqual(12)
  expect(raidLeadStyle.top).toBeGreaterThanOrEqual(12)
  await expect(page.locator('.runtime-status-bar')).toContainText('Soulcoil Ignition')
  expect(await player.locator('.character-body').evaluate(element => getComputedStyle(element, '::after').content)).toBe('none')
  const before = Number(await player.getAttribute('data-position-y'))
  await page.keyboard.down('w'); await page.waitForTimeout(300); await page.keyboard.up('w')
  expect(Number(await player.getAttribute('data-position-y'))).toBeLessThan(before)
  await expect(page.locator('.learn2d-controls')).toContainText('Main F')
  await expect(page.getByRole('button', { name: 'Main ability' })).toHaveCount(0)
  await page.keyboard.press('f')
  const attachedCast = player.locator('.actor-main-cast .arena-hud-castbar')
  await expect(attachedCast).toBeVisible()
  const castGeometry = await player.evaluate(element => {
    const playerBounds = element.getBoundingClientRect()
    const castBounds = element.querySelector('.actor-main-cast .arena-hud-castbar')!.getBoundingClientRect()
    return { playerBottom: playerBounds.bottom, castTop: castBounds.top, castWidth: castBounds.width }
  })
  expect(castGeometry.castTop).toBeGreaterThan(castGeometry.playerBottom)
  expect(castGeometry.castWidth).toBeLessThan(100)
  await expect(attachedCast).toHaveCount(0, { timeout: 2000 })
  await page.keyboard.press('f')
  await expect.poll(() => page.locator('[data-effect-id^="player-main"]').count(), { timeout: 2500 }).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Exit' }).click()

  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Train 3D" }).click()
  const arena3d = page.getByLabel('Third-person 3D training arena')
  await expect(arena3d).toHaveAttribute('data-arena-shape', 'circle')
  await expect(arena3d).toHaveAttribute('data-arena-theme', 'soulcoil')
  const setup3d = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await setup3d.getByRole('button', { name: /Tank 1, warrior/ }).click()
  await setup3d.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect(page.locator('.arena-hud-health.boss')).toContainText("Nek'zali · your aggro")
  await page.keyboard.press('f')
  const castFill = page.locator('.arena-hud-castbar i')
  await expect(castFill).toBeVisible()
  const firstWidth = await castFill.evaluate(element => Number.parseFloat((element as HTMLElement).style.width))
  await expect.poll(() => castFill.evaluate(element => Number.parseFloat((element as HTMLElement).style.width))).toBeGreaterThan(firstWidth + 10)
  await expect.poll(async () => Number(await arena3d.getAttribute('data-player-main-effect-count')), { timeout: 2500 }).toBeGreaterThan(0)
  await expect(page.locator('.arena-hud-castbar')).toHaveCount(0, { timeout: 2000 })
  await page.keyboard.press('f')
  await expect(page.locator('.arena-hud-castbar i')).toBeVisible()
})

test('keeps all eight encounters in a compact four-column desktop selector', async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 1000 })
  await page.goto('/')
  const cards = page.locator('.season2-boss-selector > button')
  await expect(cards).toHaveCount(8)
  const firstTop = (await cards.nth(0).boundingBox())?.y
  const fourthTop = (await cards.nth(3).boundingBox())?.y
  const fifthTop = (await cards.nth(4).boundingBox())?.y
  expect(firstTop).toBeDefined()
  expect(Math.abs((fourthTop ?? 0) - (firstTop ?? 0))).toBeLessThan(3)
  expect(fifthTop).toBeGreaterThan((firstTop ?? 0) + 50)
  await page.locator('.season2-boss-selector').evaluate(element => element.scrollIntoView())
  await expect(cards.first()).toBeInViewport()
  await expect(cards.nth(7)).toBeInViewport()
  await expect(cards.first().locator('.encounter-icon')).toBeVisible()
  await expect(page.locator('.season2-selected-encounter')).toHaveCount(1)
  const selectorWidth = (await page.locator('.season2-boss-selector').boundingBox())!.width
  const difficultyWidth = (await page.locator('.season2-training-difficulty').boundingBox())!.width
  expect(difficultyWidth).toBeLessThan(selectorWidth * .4)
})

test("keeps Nek'zali Well mechanics and interrupt controls in its single full fight", async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" }).click()
  const setup2d = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await expect(setup2d).toContainText('Choose role and assignment')
  await expect(setup2d).toContainText(/REALM GROUP [12]/)
  await setup2d.getByRole('button', { name: 'Start' }).click()
  await expect(page.locator('.learn2d-controls')).toContainText('Interrupt T')
  await expect(page.getByRole('button', { name: 'Interrupt', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Exit' }).click()

  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Train 3D" }).click()
  const setup3d = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await expect(setup3d).toContainText('Choose role and assignment')
  await expect(setup3d).toContainText(/REALM GROUP [12]/)
  await setup3d.getByRole('button', { name: 'Start' }).click()
  await expect(page.locator('.train3d-controls')).toContainText('Interrupt T')
  await expect(page.getByLabel('HUD action buttons')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Main ability F', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Interrupt T', exact: true })).toBeVisible()
})

test("keeps Nek'zali mechanic coaching compact and assignment-neutral before selection", async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Train 3D" }).click()
  const setup = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await setup.getByRole('button', { name: 'Start' }).click()
  const mechanic = page.locator('.arena-hud-mechanic.compact')
  await expect(mechanic).toBeVisible()
  await expect(mechanic.getByText('Mechanic', { exact: true })).toHaveCount(0)
  await expect(mechanic.getByLabel('Action state')).toHaveCount(0)
  await expect(mechanic).not.toContainText(/Take Essence Rend|assigned adds|soak group/)
  await expect(mechanic).toContainText(/Soulcoil Ignition in ~\d+s/)
  await expect(mechanic).toHaveCSS('background-color', 'rgba(5, 9, 13, 0.94)')
  await expect(mechanic).toHaveCSS('color', 'rgb(255, 244, 189)')
  await expect(page.locator('canvas')).toHaveAttribute('data-floor-material', 'cracked-soul-stone')
  expect((await mechanic.boundingBox())!.width).toBeLessThanOrEqual(270)
})

test("renders Nek'zali Phase 2 Cultists as continuous clockwise motion", async ({ page }) => {
  test.setTimeout(90_000)
  await page.clock.install()
  await page.goto('/')
  await page.getByRole('group', { name: 'Trainer difficulty' }).getByRole('button', { name: 'Test' }).click()
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" }).click()
  const setup = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await setup.getByRole('button', { name: /Ranged 1, mage/ }).click()
  await setup.getByRole('button', { name: 'Start' }).click()
  await page.clock.runFor(3_100)
  await page.clock.runFor(44_800)
  const barrageCarrier = page.locator('.contract-raid-member').filter({ has: page.locator('.platform-aura-icons[aria-label*="possession-barrage"]') })
  await expect(barrageCarrier).toHaveCount(1)
  const carrierPosition = { x: Number(await barrageCarrier.getAttribute('data-position-x')), y: Number(await barrageCarrier.getAttribute('data-position-y')) }
  const bystanderPositions = await page.locator('.contract-raid-member').evaluateAll((elements, carrierId) => elements.filter(element => element.getAttribute('data-actor-id') !== carrierId).map(element => ({ x: Number(element.getAttribute('data-position-x')), y: Number(element.getAttribute('data-position-y')) })), await barrageCarrier.getAttribute('data-actor-id'))
  expect(bystanderPositions.every(position => Math.hypot(position.x - carrierPosition.x, position.y - carrierPosition.y) > 11)).toBe(true)

  await page.clock.runFor(51_200)
  await expect(page.locator('.runtime-status-bar')).toContainText('INTERMISSION')
  const echoRaid = await page.locator('.contract-raid-member').evaluateAll(elements => elements.map(element => ({ x: Number(element.getAttribute('data-position-x')), y: Number(element.getAttribute('data-position-y')) })))
  expect(echoRaid.filter(position => Math.hypot(position.x, position.y + 34) <= 14).length).toBeGreaterThanOrEqual(15)

  await page.clock.runFor(44_000)
  await expect(page.locator('.runtime-status-bar')).toContainText('P2')
  const cultists = page.locator('[data-effect-id^="rend-"]')
  await expect(cultists).toHaveCount(2)
  const first = cultists.first()
  const samples: { x: number; y: number }[] = []
  for (let index = 0; index < 4; index += 1) {
    samples.push({ x: Number(await first.getAttribute('data-position-x')), y: Number(await first.getAttribute('data-position-y')) })
    await page.clock.runFor(250)
  }
  for (let index = 1; index < samples.length; index += 1) {
    const displacement = Math.hypot(samples[index].x - samples[index - 1].x, samples[index].y - samples[index - 1].y)
    expect(displacement).toBeGreaterThan(.1)
    expect(displacement).toBeLessThan(1)
  }
  const cross = samples[0].x * samples.at(-1)!.y - samples[0].y * samples.at(-1)!.x
  expect(cross).toBeGreaterThan(0)
})

test("makes Nek'zali Anguished Echo a resolving danger telegraph", async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" }).click()
  await page.getByRole('dialog', { name: "Nek'zali encounter setup" }).getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  const firstImpact = page.locator('[data-effect-id^="anguished-"]').first()
  await expect(firstImpact).toBeVisible({ timeout: 10_000 })
  await expect(firstImpact).toHaveCSS('border-color', 'rgb(239, 113, 130)')
  const impactId = await firstImpact.getAttribute('data-effect-id')
  await expect(page.locator(`[data-effect-id="${impactId}"]`)).toHaveCount(0, { timeout: 2500 })
})

test("keeps Nek'zali Learn 2D circular, undistorted, and movable left and right", async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: "Launch Nek'zali the Soulcoiler Learn 2D" }).click()
  const setup = page.getByRole('dialog', { name: "Nek'zali encounter setup" })
  await setup.getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })

  const board = page.getByLabel("Nek'zali raid-plan training arena")
  const geometry = await board.evaluate(element => {
    const bounds = element.getBoundingClientRect()
    return { width: bounds.width, height: bounds.height, backgroundSize: getComputedStyle(element).backgroundSize }
  })
  expect(Math.abs(geometry.width - geometry.height)).toBeLessThan(1)
  expect(geometry.backgroundSize).toBe('auto 100%, auto 100%')
  const frame = page.locator('.learn2d-arena-frame')
  const failurePanel = page.getByLabel('Recent failures')
  await expect(failurePanel).toBeVisible()
  expect(await board.locator('.runtime-failure-log').count()).toBe(0)
  const [frameBox, failureBox] = await Promise.all([frame.boundingBox(), failurePanel.boundingBox()])
  if (!frameBox || !failureBox) throw new Error('Nek\'zali arena feedback has no bounds')
  expect(failureBox.y + failureBox.height).toBeLessThanOrEqual(frameBox.y + frameBox.height + 1)

  const player = page.getByLabel(/Controlled .* player/)
  const startBox = await player.boundingBox()
  const start = Number(await player.getAttribute('data-position-x'))
  await page.keyboard.down('a'); await page.waitForTimeout(300); await page.keyboard.up('a')
  const leftBox = await player.boundingBox()
  const left = Number(await player.getAttribute('data-position-x'))
  expect(left).toBeLessThan(start)
  await page.keyboard.down('d'); await page.waitForTimeout(300); await page.keyboard.up('d')
  const returnedBox = await player.boundingBox()
  expect(Number(await player.getAttribute('data-position-x'))).toBeGreaterThan(left)
  if (!startBox || !leftBox || !returnedBox) throw new Error('Nek\'zali player has no bounds')
  expect(Math.abs((startBox.x - leftBox.x) - (returnedBox.x - leftBox.x))).toBeLessThan(3)
})

test('launches the single Entombed Sentinels full fight in separate 2D and 3D arenas', async ({ page }) => {
  await page.goto('/')
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' }).click()
  const setup2d = page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' })
  await expect(setup2d).toContainText('full fight')
  await setup2d.getByRole('button', { name: 'Healer 2, druid' }).click()
  await expect(setup2d).toContainText('Blighted Blood dispel')
  await setup2d.getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Entombed Sentinels raid-plan training arena')).toBeVisible({ timeout: 5000 })
  await expect(page.locator('.learn2d-controls > span')).toContainText('Dispel R')
  await expect(page.getByLabel('2D movement controls')).toBeVisible()
  await expect(page.locator('.learn2d-controls')).toContainText('Main F')
  await expect(page.getByRole('button', { name: 'Move forward' })).toHaveText('↑')
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  const player = page.getByLabel(/Controlled .* player/)
  await page.keyboard.press('f')
  await expect(player.locator('.actor-main-cast .arena-hud-castbar')).toBeVisible()
  await expect(page.locator('.encounter-cast-bars')).toHaveCount(0)
  await expect.poll(() => page.locator('[data-effect-id^="player-main"]').count(), { timeout: 2500 }).toBeGreaterThan(0)
  const beforeBox = await player.boundingBox()
  const before = { x: Number(await player.getAttribute('data-position-x')), y: Number(await player.getAttribute('data-position-y')) }
  await page.keyboard.down('w'); await page.waitForTimeout(300); await page.keyboard.up('w')
  const afterForwardBox = await player.boundingBox()
  const afterForward = { x: Number(await player.getAttribute('data-position-x')), y: Number(await player.getAttribute('data-position-y')) }
  expect(afterForward.y).toBeLessThan(before.y)
  expect(Math.abs(afterForward.x - before.x)).toBeLessThan(.2)
  const rightButton = page.getByRole('button', { name: 'Move right' })
  await rightButton.dispatchEvent('pointerdown'); await page.waitForTimeout(300); await rightButton.dispatchEvent('pointerup')
  const afterRightBox = await player.boundingBox()
  expect(Number(await player.getAttribute('data-position-x'))).toBeGreaterThan(afterForward.x)
  if (!beforeBox || !afterForwardBox || !afterRightBox) throw new Error('Sentinels player has no bounds')
  const verticalPixels = Math.abs(afterForwardBox.y - beforeBox.y)
  const horizontalPixels = Math.abs(afterRightBox.x - afterForwardBox.x)
  expect(Math.abs(horizontalPixels - verticalPixels)).toBeLessThan(3)
  await page.getByRole('button', { name: 'Exit' }).click()

  await page.getByRole('button', { name: 'Launch Entombed Sentinels Train 3D' }).click()
  const setup3d = page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' })
  const canvas = page.getByLabel('Third-person 3D training arena')
  await expect(canvas).toHaveAttribute('data-arena-shape', 'rectangle')
  await expect(canvas).toHaveAttribute('data-arena-theme', 'sentinels')
  await setup3d.getByRole('button', { name: 'Tank 1, warrior' }).click()
  await setup3d.getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect(page.getByLabel(/Breath of Ula'tek energy 5\d%/)).toBeVisible()
  await expect(page.getByText(/boss distance 9\d yd/i)).toBeVisible()
  await page.keyboard.press('f')
  await expect(page.locator('.arena-hud-castbar')).toBeVisible()
  await expect.poll(async () => Number(await canvas.getAttribute('data-player-main-effect-count')), { timeout: 2500 }).toBeGreaterThan(0)
})

test('removes passive Sentinels mark diamonds and keeps its Learn 2D raid telegraph conspicuous', async ({ page }) => {
  await page.clock.install()
  await page.goto('/')
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' }).click()
  await page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' }).getByRole('button', { name: 'Start' }).click()
  await page.clock.runFor(3_100)
  const raidLead = page.getByLabel('Raid lead mechanic telegraph')
  await expect(raidLead).toBeVisible()
  await expect(raidLead).toHaveCSS('background-color', 'rgba(243, 216, 113, 0.96)')
  await page.clock.runFor(10_200)
  const playerAuras = page.getByLabel(/Controlled .* player/).locator('.platform-aura-icons')
  await expect(playerAuras.locator('.platform-aura-icon.poison')).toHaveCount(0)
})

test('moves independently in all four Learn 2D directions and clears input on blur', async ({ page }) => {
  await page.goto('/')
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' }).click()
  await page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' }).getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  const player = page.getByLabel(/Controlled .* player/)
  await expect(player).toBeVisible()
  const position = async () => ({ x: Number(await player.getAttribute('data-position-x')), y: Number(await player.getAttribute('data-position-y')) })
  let before = await position()
  await page.keyboard.down('a'); await page.waitForTimeout(260); await page.keyboard.up('a')
  let after = await position(); expect(after.x).toBeLessThan(before.x)
  before = after
  await page.keyboard.down('d'); await page.waitForTimeout(420); await page.keyboard.up('d')
  after = await position(); expect(after.x).toBeGreaterThan(before.x)
  before = after
  await page.keyboard.down('s'); await page.waitForTimeout(260); await page.keyboard.up('s')
  after = await position(); expect(after.y).toBeGreaterThan(before.y)
  before = after
  await page.keyboard.down('w'); await page.waitForTimeout(260); await page.keyboard.up('w')
  after = await position(); expect(after.y).toBeLessThan(before.y)

  await page.keyboard.down('w'); await page.waitForTimeout(180)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.waitForTimeout(100)
  const stopped = await position()
  await page.waitForTimeout(300)
  expect(Math.abs((await position()).y - stopped.y)).toBeLessThan(.2)
  await page.keyboard.up('w')
})

test('keeps the wide runtime header in one line and preserves the 2D arena aspect', async ({ page }) => {
  await page.setViewportSize({ width: 2048, height: 900 })
  await page.goto('/')
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Learn 2D' }).click()
  await page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' }).getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })

  await expect(page.getByLabel('Build information')).toHaveCount(0)
  const status = page.locator('.runtime-status-bar')
  const statusBox = await status.boundingBox()
  expect(statusBox?.width).toBeGreaterThan(1900)
  const boardBox = await page.getByLabel('Entombed Sentinels raid-plan training arena').boundingBox()
  if (!boardBox) throw new Error('2D arena has no bounds')
  expect(boardBox.width / boardBox.height).toBeGreaterThan(1.45)
  await expect(page.getByRole('complementary', { name: 'Recent failures' })).toContainText('No failures yet')
  await expect(page.getByRole('complementary', { name: 'Points' })).toContainText('Not scored')
})

test('opens paired contract rooms with full-raid ground reactions and paced 3D rendering', async ({ page }) => {
  test.setTimeout(process.env.CI ? 60_000 : 30_000)
  await page.goto('/')
  await page.getByRole('button', { name: 'Open Learn 2D room' }).click()

  await expect(page.getByRole('heading', { name: 'Top-down reaction lab' })).toBeVisible()
  const entrance = page.getByRole('dialog', { name: 'Contract room entrance' })
  await expect(entrance).toBeVisible()
  await expect(page.getByLabel(/ground rune$/)).toHaveCount(4)
  await expect(page.getByLabel(/NPC$/)).toHaveCount(19)
  await expect(entrance.getByRole('group', { name: '20-player raid positions' }).getByRole('button')).toHaveCount(20)
  const player2d = page.getByLabel(/Controlled .* ranged player/)
  const lockedY = await player2d.getAttribute('data-position-y')
  await page.keyboard.down('w'); await page.waitForTimeout(220); await page.keyboard.up('w')
  await expect(player2d).toHaveAttribute('data-position-y', lockedY || '')
  await entrance.getByRole('button', { name: /Tank 1, warrior/ }).click()
  await expect(page.getByLabel(/Controlled warrior tank player/)).toBeVisible()
  await expect(page.getByLabel('tank NPC')).toHaveCount(1)
  await entrance.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByLabel('Pull countdown')).toBeVisible()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await page.keyboard.down('d')
  const displayRatePositions = await page.locator('.learn2d-character.player').evaluate(async element => {
    const values: string[] = []
    for (let frame = 0; frame < 8; frame += 1) {
      await new Promise<void>(resolve => requestAnimationFrame(() => resolve()))
      values.push((element as HTMLElement).dataset.positionX || '')
    }
    return values
  })
  await page.keyboard.up('d')
  expect(new Set(displayRatePositions).size).toBeGreaterThanOrEqual(5)
  await expect(page.getByLabel('Contract combat actions')).toHaveCount(0)
  await expect(page.locator('.learn2d-controls')).toContainText('Main F')
  await expect(page.locator('.learn2d-controls')).toContainText('Potion')
  await page.keyboard.press('f')
  await expect(page.locator('.arena-hud-castbar')).toBeVisible()
  await expect.poll(() => page.locator('[data-effect-id^="contract-player-main"]').count(), { timeout: 2500 }).toBeGreaterThan(0)
  await expect(page.locator('.learn2d-character .actor-health')).toHaveCount(1)
  await expect(page.locator('.contract-2d-boss .actor-health')).toHaveCount(1)
  await page.getByRole('button', { name: 'Exit' }).click()
  await page.getByRole('button', { name: 'Open Train 3D room' }).click()

  await expect(page.getByRole('heading', { name: 'Reaction and movement lab' })).toBeVisible()
  const contractArena = page.getByLabel('Third-person 3D training arena')
  await expect(contractArena).toBeVisible()
  await expect(contractArena).toHaveAttribute('data-world-marker-count', '4')
  const markerWobble = Number(await contractArena.getAttribute('data-marker-wobble-sample'))
  await expect.poll(async () => Number(await contractArena.getAttribute('data-marker-wobble-sample'))).not.toBeCloseTo(markerWobble, 4)
  await expect(contractArena).toHaveAttribute('data-cosmetic-cast-count', '0')
  const trainEntrance = page.getByRole('dialog', { name: 'Contract room entrance' })
  await expect(trainEntrance).toBeVisible()
  const selectedXs: number[] = []
  for (const slot of [/Tank 1, warrior/, /Healer 5, evoker/, /Melee 3, demon hunter/, /Ranged 7, evoker/]) {
    await trainEntrance.getByRole('button', { name: slot }).click()
    await expect.poll(() => contractArena.evaluate(element => Math.abs(Number((element as HTMLElement).dataset.playerX) - Number((element as HTMLElement).dataset.cameraTargetX)))).toBeLessThan(.01)
    selectedXs.push(Number(await contractArena.getAttribute('data-camera-target-x')))
  }
  expect(new Set(selectedXs).size).toBeGreaterThanOrEqual(3)
  await expect(page.locator('details.contract-lab-drawer')).not.toHaveAttribute('open', '')
  await trainEntrance.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect.poll(async () => Number(await contractArena.getAttribute('data-cosmetic-cast-count'))).toBeGreaterThan(0)
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toContainText('event 1')
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toContainText('20-player raid')
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toContainText('React')
  await expect(page.locator('.arena-hud-health.player')).toBeVisible()
  await expect(page.locator('.arena-hud-health.boss')).toBeVisible()
  const mainAction = page.getByRole('button', { name: /Main ability/ })
  await expect(mainAction).toBeVisible()
  await page.keyboard.press('p')
  await expect(mainAction).toBeDisabled()
  await page.keyboard.press('f')
  await expect(page.locator('.arena-hud-castbar')).toHaveCount(0)
  await page.keyboard.press('p')
  await mainAction.click()
  const castFill = page.locator('.arena-hud-castbar i')
  await expect(castFill).toBeVisible()
  await page.keyboard.press('p')
  const pausedCastWidth = await castFill.evaluate(element => Number.parseFloat((element as HTMLElement).style.width))
  await page.waitForTimeout(180)
  expect(await castFill.evaluate(element => Number.parseFloat((element as HTMLElement).style.width))).toBeCloseTo(pausedCastWidth, 1)
  await page.keyboard.press('p')
  await expect.poll(async () => await castFill.count() === 0 ? 100 : castFill.evaluate(element => Number.parseFloat((element as HTMLElement).style.width))).toBeGreaterThan(pausedCastWidth + 1)
  const minimumRenderFps = process.env.CI ? 10 : 30
  const maximumFrameP95Ms = process.env.CI ? 120 : 50
  await expect.poll(async () => Number(await contractArena.getAttribute('data-render-fps')), { timeout: 4000 }).toBeGreaterThanOrEqual(minimumRenderFps)
  expect(Number(await contractArena.getAttribute('data-frame-p95-ms'))).toBeLessThan(maximumFrameP95Ms)
  await expect(page.getByText(/\d+ FPS · p95/)).toBeVisible()
})

test('uses independently rebound movement keys, shared HUD settings, and paused camera look in the Sentinels 3D full fight', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Keys & Mouse' }).click()
  const inputPanel = page.getByRole('group', { name: 'Input bindings' })
  await expect(inputPanel).toBeVisible()
  expect((await inputPanel.boundingBox())!.height).toBeLessThan(520)
  const learnBindings = inputPanel.getByRole('region', { name: 'Learn 2D movement' })
  const trainBindings = inputPanel.getByRole('region', { name: 'Train 3D movement' })
  const mouseBindings = inputPanel.getByRole('region', { name: 'Mouse camera' })
  const [learnBox, trainBox, mouseBox] = await Promise.all([learnBindings.boundingBox(), trainBindings.boundingBox(), mouseBindings.boundingBox()])
  expect(learnBox?.y).toBeCloseTo(trainBox!.y, 0)
  expect(trainBox?.y).toBeCloseTo(mouseBox!.y, 0)
  const movementButtons = inputPanel.getByRole('button', { name: /Rebind (Learn 2D|Train 3D) movement/ })
  expect(await movementButtons.first().evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThanOrEqual(12)
  expect((await movementButtons.first().boundingBox())?.height).toBe((await movementButtons.nth(1).boundingBox())?.height)
  await page.getByRole('button', { name: 'Rebind Train 3D movement forward, current W' }).click()
  await page.keyboard.press('ArrowUp')
  await page.reload()
  await page.getByRole('button', { name: 'Keys & Mouse' }).click()
  await expect(page.getByRole('button', { name: 'Rebind Train 3D movement forward, current ArrowUp' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rebind Learn 2D movement forward, current W' })).toBeVisible()
  await page.getByRole('button', { name: 'HUD' }).click()
  await expect(page.getByRole('complementary', { name: 'Training HUD' })).toHaveCount(0)
  await expect(page.getByLabel('Draggable HUD preview')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Player health + cooldowns' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Show objective' })).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'Show timer' })).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'Show position' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Game settings' }).click()
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Train 3D' }).click()

  await expect(page.getByRole('heading', { name: 'Entombed Sentinels full fight' })).toBeVisible()
  await expect(page.locator('canvas')).toHaveAttribute('data-floor-material', 'cracked-temple-stone')
  await page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' }).getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  await expect(page.getByRole('dialog', { name: 'Contract room entrance' })).toHaveCount(0)
  await expect(page.locator('.contract-lab-drawer')).toHaveCount(1)
  const arena = page.getByLabel('Third-person 3D training arena')
  await expect(arena).toBeVisible()
  await arena.hover()
  await page.mouse.wheel(0, 300)
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('midnight-s2:training-settings:v1') || '{}').camera?.zoom ?? 0)).toBeGreaterThan(22)
  await expect(page.getByRole('complementary', { name: 'Training HUD' }).getByText('Mechanic')).toBeVisible()
  await page.keyboard.press('p')
  await expect(page.getByRole('button', { name: /Resume P/ })).toBeVisible()
  const pausedAt = { x: await arena.getAttribute('data-player-x'), z: await arena.getAttribute('data-player-z') }
  const viewportBounds = await arena.boundingBox()
  if (!viewportBounds) throw new Error('Sentinels viewport has no bounds')
  const lookStart = { x: viewportBounds.x + viewportBounds.width / 2, y: viewportBounds.y + viewportBounds.height / 2 }
  const facingBeforeLook = Number(await arena.getAttribute('data-player-facing'))
  await page.mouse.move(lookStart.x, lookStart.y)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(lookStart.x + 80, lookStart.y)
  await page.mouse.up({ button: 'right' })
  await expect.poll(async () => Number(await arena.getAttribute('data-player-facing'))).toBeGreaterThan(facingBeforeLook + .2)
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(300); await page.keyboard.up('ArrowUp')
  await expect(arena).toHaveAttribute('data-player-x', pausedAt.x || '')
  await expect(arena).toHaveAttribute('data-player-z', pausedAt.z || '')
  await page.keyboard.press('p')
  await page.keyboard.down('ArrowUp')
  await page.waitForTimeout(500)
  await page.keyboard.up('ArrowUp')
  await expect(page.getByRole('complementary', { name: 'Training HUD' }).getByText('Position')).toHaveCount(0)
  expect(await arena.getAttribute('data-player-z')).not.toBe(pausedAt.z)
})

test('Season 2 shell HUD boxes follow the pointer and persist on release', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'HUD' }).click()
  const preview = page.getByLabel('Draggable HUD preview')
  const player = page.getByRole('button', { name: 'Player health + cooldowns' })
  await player.hover()
  const before = await player.boundingBox()
  if (!before) throw new Error('HUD player box has no bounds')
  await page.mouse.down()
  await page.mouse.move(before.x + before.width / 2 + 160, before.y + before.height / 2 + 60, { steps: 3 })
  await expect.poll(async () => (await player.boundingBox())!.x - before.x, { timeout: 500 }).toBeGreaterThan(145)
  await expect.poll(async () => (await player.boundingBox())!.y - before.y, { timeout: 500 }).toBeGreaterThan(45)
  await page.mouse.up()
  const previewBox = await preview.boundingBox()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('midnight-s2:training-settings:v1') || '{}').hud?.layout?.player)
  if (!previewBox) throw new Error('HUD preview has no bounds')
  expect(saved.x).toBeGreaterThan(35)
  await expect.poll(() => player.evaluate(element => Number.parseFloat((element as HTMLElement).style.left))).toBe(saved.x)
  const after = await player.boundingBox()
  if (!after) throw new Error('Moved HUD player box has no bounds')
  expect(Math.abs((after.x - before.x) - (saved.x - 21) / 100 * previewBox.width)).toBeLessThan(2)
  expect(Math.abs((after.y - before.y) - (saved.y - 53) / 100 * previewBox.height)).toBeLessThan(2)
  expect(saved.y).toBeGreaterThan(53)
  await expect(preview).toBeVisible()
})

test('keeps left orbit independent, aligns on right press, and moves with both mouse buttons', async ({ page }) => {
  await page.goto('/')
  await selectBoss(page, 'Entombed Sentinels')
  await page.getByRole('button', { name: 'Launch Entombed Sentinels Train 3D' }).click()
  await page.getByRole('dialog', { name: 'Entombed Sentinels encounter setup' }).getByRole('button', { name: 'Start' }).click()
  await expect(page.getByLabel('Pull countdown')).toHaveCount(0, { timeout: 4000 })
  const arena = page.getByLabel('Third-person 3D training arena')
  const bounds = await arena.boundingBox()
  if (!bounds) throw new Error('3D arena has no bounds')
  const center = { x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 }
  const initialFacing = Number(await arena.getAttribute('data-player-facing'))
  await page.mouse.move(center.x, center.y)
  await page.mouse.down({ button: 'left' })
  await page.mouse.move(center.x + 90, center.y)
  await page.mouse.up({ button: 'left' })
  expect(Number(await arena.getAttribute('data-player-facing'))).toBeCloseTo(initialFacing, 2)

  await page.mouse.down({ button: 'right' })
  await expect.poll(async () => Number(await arena.getAttribute('data-player-facing'))).toBeGreaterThan(initialFacing + .25)
  const alignedFacing = Number(await arena.getAttribute('data-player-facing'))
  await page.mouse.move(center.x + 130, center.y)
  await expect.poll(async () => Number(await arena.getAttribute('data-player-facing'))).toBeGreaterThan(alignedFacing)

  const before = { x: Number(await arena.getAttribute('data-player-x')), z: Number(await arena.getAttribute('data-player-z')) }
  await page.mouse.down({ button: 'left' })
  await expect.poll(async () => {
    const current = { x: Number(await arena.getAttribute('data-player-x')), z: Number(await arena.getAttribute('data-player-z')) }
    return Math.hypot(current.x - before.x, current.z - before.z)
  }).toBeGreaterThan(2)
  await page.mouse.up({ button: 'left' })
  await page.mouse.up({ button: 'right' })
  await expect(arena).toHaveAttribute('data-player-marker', 'humanoid-chevron')
})

test('does not expose the retired Season 1 reference route', async ({ page }) => {
  await page.goto('/?reference=lura-v0.9.1')
  await expect(page.getByRole('heading', { name: 'Midnight Season 2 Trainer' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'L’ura Trainer' })).toHaveCount(0)
})
