import RAID_PLAN from '../../../inbox/the-coiled-altar.png'
import type { EvidenceEncounterDefinition } from '../../platform/encounters/evidenceFullFight'

export const definition = {
  id: 'the-coiled-altar', name: 'The Coiled Altar', order: 7,
  summary: "Route Zul'jan's venom into frontal cleanup, survive Malacrass manifestations, and intercept Soulbinding fragments.",
  sourceAsOf: '2026-08-16', sourceNote: 'Maintained pre-live guide and PTR spell data; exact counts, geometry, and recurrence remain configurable.',
  arenaKind: 'rectangle', arena2dId: 'coiled_altar_raidplan', arena2dLabel: 'Coiled Altar supplied raid plan', learn2dBackground: RAID_PLAN, boardClass: 'coiled-altar-2d-board', start: { x: 0, z: 20 },
  arena3d: { id: 'coiled_altar_world', label: 'Coiled Altar rectangular platform', shape: 'rectangle', width: 100, depth: 60, anchors: [{ id: 'seal', label: 'Central altar seal', x: 0, z: 0 }, { id: 'zuljan', label: "Zul'jan", x: -20, z: -10 }, { id: 'malacrass', label: 'Hex Lord Malacrass', x: 20, z: -10 }, { id: 'escape', label: 'Guillotine escape', x: 44, z: 15 }], theme: { kind: 'coiled-altar', layout: 'coiled-altar', material: 'ritual-altar-stone', floor: '#25201c', boundary: '#b18b5e', accent: '#d3b577', center: '#6e4c36', fog: 'none' } },
  bosses: [{ id: 'altar-zuljan', name: "Zul'jan", position: { x: -20, z: -10 }, color: '#78bb61' }, { id: 'altar-malacrass', name: 'Hex Lord Malacrass', position: { x: 20, z: -10 }, color: '#9270c0' }],
  phaseNames: ["Zul'jan", 'Hex Lord Malacrass', 'Soulbinding', 'Coiled Union'], resource: { label: 'Venom objects', initial: 0, maximum: 6, lethal: 7 },
  tacticFields: [{ id: 'venom-lanes', label: 'Venom cleanup lanes', kind: 'region', value: ['left-sever', 'right-sever'] }, { id: 'guillotine-groups', label: 'Guillotine groups', kind: 'group', value: ['group-one', 'group-two'] }, { id: 'fragment-owners', label: 'Soul fragment owners', kind: 'action-owner', value: 'player' }],
  steps: [
    { id: 'fangs-safe', label: 'Fangs of the Coiled Altar', prompt: 'Move into the central hourglass while Noxious Ground expands.', advice: 'Reach the seal-side safe region before the poison closes in.', duration2d: 5, duration3d: 7, position: { x: 0, z: 0 }, radius: 9, intent: 'enter', color: '#d0b36b' },
    { id: 'toxic-deluge', label: 'Toxic Deluge', prompt: 'Dodge the impact that creates your assigned Coalesced Venom.', advice: 'Leave the four-yard impact before collecting its venom.', duration2d: 4, duration3d: 5, position: { x: -27, z: 12 }, radius: 7, intent: 'avoid', color: '#7dbb55', resourceDelta: 1 },
    { id: 'volatile-venom', label: 'Volatile Venom', prompt: 'Collect the globule and carry its five-yard danger circle away.', advice: 'Enter the venom only when your carrier lockout is clear.', duration2d: 5, duration3d: 6, position: { x: -30, z: 12 }, radius: 5, intent: 'enter', color: '#8ac65e' },
    { id: 'venom-deposit', label: 'Venom deposit', prompt: 'Drop the carried venom inside the future Sever cleanup lane.', advice: 'Reach the left frontal lane before Volatile Venom expires.', duration2d: 5, duration3d: 6, position: { x: -20, z: -20 }, radius: 6, intent: 'enter', color: '#a4cf62' },
    { id: 'sever', label: 'Sever', prompt: 'Leave Zul’jan’s frontal while it destroys the prepared venom.', advice: 'Keep every non-tank outside the cleanup cone.', duration2d: 4, duration3d: 5, position: { x: -20, z: -12 }, radius: 12, intent: 'avoid', color: '#d6a45f', resourceDelta: -1 },
    { id: 'guillotine', label: 'Guillotine', prompt: 'Join the assigned five-player soak around the marked target.', advice: 'Reach the nine-yard group soak before the axe lands.', duration2d: 5, duration3d: 6, position: { x: 0, z: 16 }, radius: 9, intent: 'enter', color: '#d66f5c' },
    { id: 'widows-kiss', label: "Widow's Kiss", prompt: 'Run far from the axe epicenter after the successful soak.', advice: 'Reach the outer escape anchor before the forty-yard eruption.', duration2d: 6, duration3d: 8, position: { x: 44, z: 15 }, radius: 6, intent: 'enter', color: '#e1b35f' },
    { id: 'dreadmarch', label: 'Dreadmarch', prompt: 'Walk against the forced march and stop before the platform edge.', advice: 'Reach the central recovery anchor while the gaze controls movement.', duration2d: 6, duration3d: 8, position: { x: 0, z: -14 }, radius: 7, intent: 'enter', color: '#a681d0' },
    { id: 'manifestation', label: 'Manifestation of Dread', prompt: 'Keep the fixating manifestation away from contact and frontal cleanup.', advice: 'Leave the manifestation contact zone before it knocks you off.', duration2d: 5, duration3d: 6, position: { x: 22, z: 4 }, radius: 9, intent: 'avoid', color: '#9d72bd' },
    { id: 'soulbinding', label: 'Soulbinding', prompt: 'Use Main on your assigned Soul Fragment before it reaches Malacrass.', advice: 'Intercept the fragment and use the declared Main action.', duration2d: 6, duration3d: 7, position: { x: 0, z: 0 }, radius: 6, intent: 'action', color: '#c3a6e4', requiredAction: 'mainAbility' },
    { id: 'blighted-sever', label: 'Blighted Sever', prompt: 'Leave the combined frontal while prepared venom and manifestations are cleared.', advice: 'Keep the raid outside the combined cleanup line.', duration2d: 5, duration3d: 6, position: { x: 0, z: -10 }, radius: 13, intent: 'avoid', color: '#b88b5e' },
    { id: 'coiled-union', label: 'Coiled Union', prompt: 'Return to the altar seal as both boss systems overlap.', advice: 'Finish inside the central safe region without touching residual hazards.', duration2d: 5, duration3d: 7, position: { x: 0, z: 0 }, radius: 9, intent: 'enter', color: '#d0b36b' },
  ],
} as const satisfies EvidenceEncounterDefinition
