import type { EvidenceEncounterDefinition } from '../../platform/encounters/evidenceFullFight'

export const definition = {
  id: 'sszorak', name: 'Sszorak', order: 5,
  summary: 'Read randomized Apex attacks, place four cysts, pair Crosswinds, and counter the ordered Maelstrom winds.',
  sourceAsOf: '2026-08-16', sourceNote: 'Maintained pre-live guide and PTR spell data; exact encounter cadence remains configurable.',
  arenaKind: 'circle', arena2dId: 'sszorak_wind_platform', arena2dLabel: 'Sszorak circular wind platform', boardClass: 'sszorak-2d-board', start: { x: 0, z: 24 },
  arena3d: { id: 'sszorak_wind_world', label: 'Sszorak wind platform', shape: 'circle', width: 92, depth: 92, anchors: [{ id: 'center', label: 'Boss center', x: 0, z: 0 }, { id: 'cyst-one', label: 'Cyst one', x: -28, z: -10 }, { id: 'cyst-two', label: 'Cyst two', x: 28, z: -10 }, { id: 'cyst-three', label: 'Cyst three', x: 0, z: 34 }], theme: { kind: 'sszorak', layout: 'wind-platform', material: 'serpent-wind-stone', floor: '#202621', boundary: '#89b274', accent: '#b5dc73', fog: 'none' } },
  bosses: [{ id: 'sszorak-boss', name: 'Sszorak', position: { x: 0, z: 0 }, color: '#79bd6f' }],
  stepOrderVariants: [
    ['apex-ravage-one', 'apex-mutilate-one', 'apex-ravage-two', 'apex-tempest', 'apex-mutilate-two', 'serpents-fury', 'virulence', 'venomous-surge-one', 'raging-crosswinds', 'venomous-surge-two', 'maelstrom-one', 'maelstrom-two', 'maelstrom-three'],
    ['apex-mutilate-one', 'apex-ravage-one', 'apex-tempest', 'apex-mutilate-two', 'apex-ravage-two', 'serpents-fury', 'virulence', 'venomous-surge-one', 'raging-crosswinds', 'venomous-surge-two', 'maelstrom-one', 'maelstrom-two', 'maelstrom-three'],
    ['apex-ravage-one', 'apex-tempest', 'apex-mutilate-one', 'apex-mutilate-two', 'apex-ravage-two', 'serpents-fury', 'virulence', 'venomous-surge-one', 'raging-crosswinds', 'venomous-surge-two', 'maelstrom-one', 'maelstrom-two', 'maelstrom-three'],
  ],
  phaseNames: ['Apex and Fury', 'Cysts and Crosswinds', 'Howling Maelstrom'], resource: { label: 'Cysts prepared', initial: 0, maximum: 4, lethal: 6 },
  tacticFields: [{ id: 'mutilate-groups', label: 'Mutilate groups', kind: 'group', value: ['group-a', 'group-b'] }, { id: 'crosswind-pairs', label: 'Crosswinds pairs', kind: 'pair', value: ['pair-a', 'pair-b'] }, { id: 'cyst-order', label: 'Maelstrom cyst order', kind: 'region', value: ['cyst-one', 'cyst-two', 'cyst-three', 'cyst-four'] }],
  steps: [
    { id: 'apex-ravage-one', label: 'Apex Predator: Ravage', prompt: 'Leave the white Ravage frontal and preserve the active tank.', advice: 'Read the white frontal and move outside its cone.', duration2d: 4, duration3d: 5, position: { x: 0, z: 8 }, radius: 11, intent: 'avoid', color: '#e9ede4' },
    { id: 'apex-mutilate-one', label: 'Apex Predator: Mutilate A', prompt: 'Join your first assigned green Mutilate intercept group.', advice: 'Enter the highlighted group soak before the frontal resolves.', duration2d: 4, duration3d: 5, position: { x: -14, z: 10 }, radius: 10, intent: 'enter', color: '#75c779' },
    { id: 'apex-tempest', label: 'Apex Predator: Tempest', prompt: 'Dodge the outward and returning Tempest lane.', advice: 'Track the tornado return and leave its highlighted lane.', duration2d: 4, duration3d: 5, position: { x: 14, z: 10 }, radius: 8, intent: 'avoid', color: '#a8d8ce' },
    { id: 'apex-ravage-two', label: 'Apex Predator: Ravage repeat', prompt: 'Respect the active Ravage vulnerability and leave the redirected white frontal.', advice: 'Do not take consecutive Ravages while the vulnerability is active.', duration2d: 4, duration3d: 5, position: { x: 6, z: 9 }, radius: 11, intent: 'avoid', color: '#e9ede4' },
    { id: 'apex-mutilate-two', label: 'Apex Predator: Mutilate B', prompt: 'Join the alternate green Mutilate intercept group.', advice: 'Alternate soak groups and enter the highlighted frontal.', duration2d: 4, duration3d: 5, position: { x: 14, z: 10 }, radius: 10, intent: 'enter', color: '#75c779' },
    { id: 'serpents-fury', label: "Serpent's Fury", prompt: 'Join the late Fury stack before Rage reaches 100.', advice: 'Reach the marked player late enough to reset Rage safely.', duration2d: 5, duration3d: 6, position: { x: 0, z: 20 }, radius: 8, intent: 'enter', color: '#efc95e' },
    { id: 'virulence', label: 'Virulence', prompt: 'Spread immediately after To the Slaughter.', advice: 'Leave the stack and take Virulence to the outer lane.', duration2d: 4, duration3d: 5, position: { x: -32, z: 0 }, radius: 8, intent: 'enter', color: '#85c964' },
    { id: 'venomous-surge-one', label: 'Venomous Surge', prompt: 'Place the first Viscous Cyst at its assigned outer anchor.', advice: 'Reach the outer cyst marker before the ten-second debuff expires.', duration2d: 6, duration3d: 8, position: { x: 32, z: 0 }, radius: 6, intent: 'enter', color: '#86bd54', resourceDelta: 1 },
    { id: 'raging-crosswinds', label: 'Raging Crosswinds', prompt: 'Align with the matching partner, then let both trajectories collide.', advice: 'Reach the partner trajectory without pre-stacking in the explosion.', duration2d: 6, duration3d: 8, position: { x: 0, z: -26 }, radius: 7, intent: 'enter', color: '#8ed4d1', launchVelocity: 5.4 },
    { id: 'venomous-surge-two', label: 'Remaining Cysts', prompt: 'Place the remaining cysts without overlapping poison residue.', advice: 'Preserve the ordered Maelstrom anchors.', duration2d: 6, duration3d: 8, position: { x: 0, z: 35 }, radius: 6, intent: 'enter', color: '#86bd54', resourceDelta: 3 },
    { id: 'maelstrom-one', label: 'Howling Maelstrom I', prompt: 'Trigger cyst one on the side opposing the first wind.', advice: 'Use the first announced cyst to counter the first wind.', duration2d: 5, duration3d: 6, position: { x: -28, z: -10 }, radius: 7, intent: 'enter', color: '#b8e073', launchVelocity: 4.8 },
    { id: 'maelstrom-two', label: 'Howling Maelstrom II', prompt: 'Reposition and trigger cyst two against the second wind.', advice: 'Follow the visible order instead of taking the nearest cyst.', duration2d: 5, duration3d: 6, position: { x: 28, z: -10 }, radius: 7, intent: 'enter', color: '#b8e073', launchVelocity: 4.8 },
    { id: 'maelstrom-three', label: 'Howling Maelstrom III', prompt: 'Use cyst three, then prepare the fourth counter-knock.', advice: 'Reach the final ordered cyst before the wind removes the raid.', duration2d: 5, duration3d: 6, position: { x: 0, z: 34 }, radius: 7, intent: 'enter', color: '#b8e073', launchVelocity: 4.8 },
  ],
} as const satisfies EvidenceEncounterDefinition
